version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: logistica_bd
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: logistica_back
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - PYTHONIOENCODING=utf-8
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: logistica_front
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - backend

volumes:
  pgdata2:
